### ISSUE TITLE
Run on my server

### ISSUE THREAD

**Issue by gridworkz** [Udala/docforever#1]
Hi:

How do I install this on my own server?

Cheers,
Dave

**Comment by Udala** [comment]
Try this for documentation about the Google App Engine Python Standard Environment and deployment at Google Cloud.
https://cloud.google.com/appengine/docs/python/resources

If your prefer, it is also possible to run docforever locally:
1) Download the Google App Engine SDK for Python
https://cloud.google.com/appengine/downloads
2) Run the dev_appserver.py
`dev_appserver.py --storage_path=<path to persistent storage> <path to app.yaml>`

Example for Linux:
`./dev_appserver.py --storage_path=/home/myaccount/mystorage/ /home/myaccount/docforever`

3) You must also modify the `secret.py` file to provide your Bitcoin addresses, its associated private keys and scriptPubKeys. More info about how this works on the comments on the secret.py file. This is necessary to pay the once a day Bitcoin fee. A normal fee is 0.00005 BTC , which adds up to 4 cents in US dollars per broadcast (one broadcast per day).

4) You must also add the UTXOs (Unspent Transaction Outputs) to the `/batch/inputs/testUtxoMain.txt` file.
The testUtxoMain.txt file is a multi-line text file.The contents of each line is separated by commas. The first element of the line is the txid of the UTXO, the second element is the vout of that UTXO, the third element is the fee to Bitcoin miners (5000 satoshis which is equivalent to 0.00005 BTC), the fourth element is the Bitcoin address that has access to that UTXO. Obviously, that address must also be present at the secret.py file

5) Add the contents of the testUtxoMain.txt file to the permanent storage by running `/batch/importUtxo.py` . You can run it on the _Google App Engine interactive console_ in your local installation.

That's it! As you see, you need some Bitcoin knowledge for deployment but once you know that, the application can be deployed anywhere. The cost of the deployment would cost you around 4 or 5 cents in US dollars per day paid in Bitcoins. That is the cost of the daily message to the network (defined by cron.yaml) . Each message can notarize thousands of documents.

Cheers,
udala

**Comment by gridworkz** [comment]
Hi Udala:

Thanks! for the detailed instructions - much appreciated.

Cheers,
Dave

**Comment by Udala** [comment]
You are welcome!
